Insert Into COUNTRY_MASTER Values(1,'+91','India');
Insert Into COUNTRY_MASTER Values(2,'+1','Usa');
Insert Into STATES_MASTER Values(1,1,'Andhra Pradesh');
Insert Into STATES_MASTER Values(2,1,'Karnataka');
Insert Into STATES_MASTER Values(3,1,'Maharashtra');
Insert Into STATES_MASTER Values(4,1,'Gujarat');
Insert Into STATES_MASTER Values(5,1,'Rajasthan');
Insert Into STATES_MASTER Values(6,2,'New Jersy');
Insert Into STATES_MASTER Values(7,2,'Ohio');
Insert Into CITIES_MASTER Values(1,'Vizag',1);
Insert Into CITIES_MASTER Values(2,'Guntur',1);
Insert Into CITIES_MASTER Values(3,'Banglore',2);
Insert Into CITIES_MASTER Values(4,'Mysore',2);
Insert Into CITIES_MASTER Values(5,'Mumbai',3);
Insert Into CITIES_MASTER Values(6,'Pune',3);
Insert Into CITIES_MASTER Values(7,'Akola',3);
Insert Into CITIES_MASTER Values(8,'Yavatmal',3);
Insert Into CITIES_MASTER Values(9,'Ahemedabad',4);
Insert Into CITIES_MASTER Values(10,'Surat',4);
Insert Into CITIES_MASTER Values(11,'Gandhi Nagar',4);
Insert Into CITIES_MASTER Values(12,'Jaipur',5);
Insert Into CITIES_MASTER Values(13,'Udaipur',5);
Insert Into CITIES_MASTER Values(14,'Maywood',6);
Insert Into CITIES_MASTER Values(15,'Westwood',6);
Insert Into CITIES_MASTER Values(16,'Oakwood',7);
Insert Into CITIES_MASTER Values(17,'Cuyahoga County',7);